//Load this file after json2.js and before lookup.js
/**
 *	All literals are entered here in order to facilitate localization
 *	Entries are put in four associative arrays (JSON objects): rules, explanations, and displays
 *	Each entry is in the format "key":"value"
 *	Translate this file and the HTML files. Javascript files other than this do not need translation
 *	Translate "value" but not "key"
 *	@see	#rules
 *	@see	#explanations
 *	@see	#displays
 *	@author	IslamicSoftware.org
 *	@since	September 2020
*/
/**
 *	Rules of inheritance. 
 *	Listed as one long JSON object simulating an associative array keyed by an Id,
 *	e.g., "_Daughter_":"text explaining the rules of inheritance for daughters".
 */
rules = {
"_Son_":"<em>Anak laki-laki</em> adalah ahli waris yang paling berhak dan diklasifikasikan sebagai kerabat ('Asaba'). Mereka bersaudara dengan anak perempuan dengan perbandingan 2:1. Jika tidak ada anak perempuan, mereka mendapatkan sisanya setelah ahli waris yang disebutkan mendapatkan bagian yang disebutkan",

"_Daughter_":"<em>Anak perempuan</em> disebut ahli waris, yaitu, mereka disebutkan dalam Quran sebagai ahli waris yang harus mewarisi. Jika ahli waris yang lain termasuk anak laki-laki, mereka mewarisi setengah dari apa yang diwarisi oleh anak laki-laki. Itu disebut agnation 1:2 ('Ta'sib'). Jika tidak, jika hanya ada satu anak perempuan, dia mewarisi setengah dari harta warisan. Jika ada lebih, mereka berbagi secara merata dalam dua pertiga dari harta warisan (Sabeq[1])",

"_Grandson_":"<em>Anak laki-laki dari anak laki-laki</em> hanya menjadi ahli waris yang memenuhi syarat jika tidak ada anak laki-laki langsung. Seperti anak laki-laki, mereka diklasifikasikan sebagai kerabat. Jika tidak ada anak perempuan yang selamat, anak laki-laki bersaudara dengan anak perempuan dari anak laki-laki dengan perbandingan 2:1. Jika tidak ada anak perempuan dari anak laki-laki yang selamat, mereka mendapatkan sisanya setelah ahli waris yang disebutkan mendapatkan bagian yang disebutkan",

"_Granddaughter_":"<em>Anak perempuan dari anak laki-laki</em>. Jika anak laki-laki dari pewaris selamat, anak perempuan dari anak laki-laki tidak mewarisi. Jika anak laki-laki dari anak laki-laki tidak bertahan hidup tetapi satu anak perempuan bertahan hidup, anak perempuan itu mendapat bagian bernama setengah dan anak perempuan dari anak laki-laki berbagi seperenam, sehingga bersama-sama mereka menyelesaikan dua pertiga seolah-olah mereka bersama-sama adalah dua anak perempuan. Situasi ini disebut 'perempuan agnation'. Tetapi jika seorang anak laki-laki selamat, ia memiliki perbandingan 2:1 dengan anak-anak perempuan dari anak laki-laki dalam sisa setelah anak perempuan dari orang yang meninggal itu mendapat bagian namanya dari setengahnya. Jika dua atau lebih anak perempuan dari orang yang meninggal selamat, anak perempuan dari anak laki-laki tidak mewarisi (karena dua pertiga sudah diberikan kepada anak perempuan langsung) kecuali jika ada anak laki-laki dari anak laki-laki, atau anak laki-laki dari anak laki-laki dll, dalam hal ini mereka bersaudara. dengan perbandingan 1:2 dengan sisa keturunan laki-laki (Sabeq[1])",

"_Husband_":"<em>Suami</em> disebutkan dalam Quran sebagai ahli waris yang harus mewarisi. Bagiannya adalah setengah dari harta warisan jika almarhum, mendiang istrinya, tidak memiliki anak. Jika tidak, bagiannya adalah seperempat dari harta (Sabeq[1])",

"_Wife_":"<em>Istri</em> disebutkan dalam Quran sebagai ahli waris yang harus mewarisi. Bagiannya adalah seperempat dari harta warisan jika orang yang meninggal, mendiang suaminya, tidak memiliki anak. Jika tidak, bagiannya adalah seperdelapan dari harta warisan. Jika ada lebih dari seorang istri yang pada akhirnya belum diceraikan, sampai empat, mereka berbagi sama dalam seperempat atau seperdelapan bagian. Jika ada lebih dari empat orang yang pada akhirnya tidak diceraikan, hanya empat yang pertama saja yang sah dan karenanya dianggap sah.<br/>Jika istri yang masih hidup telah diceraikan oleh si pewaris tetapi masih dalam masa tenggang ('Idda'), dia mewarisi. Dalam mazhab Hanbali, seorang istri yang diceraikan sebelum syahadat dan yang pindah masih mewarisi jika orang yang meninggal tidak menikahi wanita lain setelahnya. Hukum Mesir juga mengizinkan seorang istri yang akhirnya diceraikan, yaitu diceraikan untuk ketiga kalinya, jika dia masih dalam masa tenggang dan tidak menyetujui perceraian, itu memungkinkan dia mewarisi (Sabeq[1])",

"_Father_":"<em>Ayah</em> adalah pewaris bernama, yaitu, ia disebutkan dalam Al-Qur'an sebagai ahli waris yang harus mewarisi. Jika ahli waris lainnya termasuk anak laki-laki, atau anak laki-laki dari anak laki-laki, dll, ayah mendapat seperenam dari warisan. Jika ahli waris termasuk anak perempuan, atau anak perempuan dari anak laki-laki, dll, dan tidak ada keturunan laki-laki, maka ayah mendapat seperenam ditambah apa yang tersisa setelah ahli waris yang disebutkan lainnya mendapatkan bagian yang disebutkan. Jika ahli waris tidak termasuk anak-anak, maka ia meniadakan pada apa yang tersisa setelah ahli waris lain yang bernama mendapatkan bagian yang disebutkannya (Sabeq[1])",

"_Mother_":"<em>Ibu</em> disebutkan dalam Quran sebagai ahli waris yang harus mewarisi. Dia mendapat seperenam dari warisan jika ahli waris lainnya termasuk anak atau cucu atau dua saudara kandung (tiga menurut pendapat Ibnu Hazm). Jika tidak ada ahli waris yang selamat, dia mendapat sepertiga dari harta warisan. Dia mengambil sepertiga dari sisanya jika ahli waris lainnya termasuk pasangan dan ayah. Situasi terakhir ini biasa dikenal dengan kasus Gharraia (Omaria) (Sabeq[1]). Ibn Hazm berpendapat bahwa dia mendapat sepertiga dari harta bahkan dalam situasi itu",

"_Grandfather_":"<em>Ayah dari ayah</em> diklasifikasikan sebagai saudara laki-laki. Ayah dari ibu diklasifikasikan sebagai saudara dari ibu. Ayah dari ayah tidak mewarisi jika ayah selamat. Jika ayah tidak bertahan, ayah dari ayah mewarisi bagian ayah - dengan beberapa pengecualian: a. Ibu dari ayah memang mewarisi dengan ayah dari ayah, tetapi dia tidak dengan ayah. b. Dalam kasus dua orang tua dan pasangan (kasus yang dikenal sebagai Omaria), ibu mendapat sepertiga dari sisanya. Sebaliknya, jika kasusnya termasuk ayah dari ayah, bukan ayah, maka ibu mewarisi sepertiga dari seluruh harta warisan. Ibn Abbas (RA) dan Ibn Hazm tidak setuju. Keduanya berpendapat bahwa ibu mendapat sepertiga dari sisanya dalam kedua situasi. c. Saudara kandung tidak mewarisi dengan ayah, tetapi mereka mewarisi ayah dari ayah. Abu Hanifah tidak setuju. Dia berpendapat bahwa saudara kandung tidak mewarisi dengan ayah dari ayah juga. Hukum Mesir memungkinkan saudara kandung mewarisi dengan ayah dari ayah melalui agnation dan ayah dari ayah dijamin minimal seperenam dari warisan, tunduk pada kemungkinan pembagian kembali jika harta warisan kelebihan permintaan (Sabeq[1])",

"_Grandmother_":"<em>Nenek</em> berbagi seperenam dari warisan jika mereka berasal dari generasi yang sama. Jika salah satu dari mereka adalah generasi yang lebih junior, generasi yang lebih muda mendapat yang keenam penuh dan generasi yang lebih tua dirampas. Jika ahli waris lainnya termasuk ibu, nenek dirampas. Jika ahli waris lainnya termasuk ayah (atau ayah dari ayah), ibunya dirampas (Sabeq[1])",

"_FullBrother_":"<em>Saudara laki-laki kandung</em> bersaudara di sisa warisan jika ada. Jika ada saudara perempuan penuh, maka setiap saudara laki-laki berbagi dengan setiap saudara perempuan dengan perbandingan 2:1",

"_FullSister_":"<em>Saudara perempuan kandung</em>. Jika satu, dia mendapat setengah jika tidak ada sanak saudara laki-laki. Jika lebih dari satu, mereka berbagi dua pertiga. Jika ada saudara laki-laki, saudara perempuan penuh saudara kandung dengan mereka dengan perbandingan 1:2. Jika tidak ada saudara laki-laki, tetapi keturunan perempuan, saudara perempuan penuh mewarisi sisanya setelah bagian yang disebutkan dari keturunan perempuan. Mereka tidak mewarisi dengan keturunan laki-laki atau ayah. Abu-Haneefa menambahkan ayah dari ayah (Sabeq[1])",

"_HalfBrother_":"<em>Saudara laki-laki tiri dari ayah</em> bersaudara dengan saudara tiri dari ayah di sisa harta warisan jika ada dan jika tidak ada saudara kandung",

"_HalfSister_":"<em>Saudara tiri dari ayah</em> tidak mewarisi dengan ayah, anak, ayah dari ayah, anak dari anak atau saudara kandung. Jika seorang anak perempuan atau anak perempuan dari anak laki-laki selamat serta satu saudara perempuan kandung, saudara perempuan penuh bersama dengan keturunan perempuan dianggap sebagai saudara laki-laki penuh dan akibatnya seorang saudara kandung dalam sisanya dan saudara tiri dari ayah tidak mewarisi. Hal ini juga mengikuti bahwa agnate virtual ini (secara hukum disebut agnation dengan 'Asaba ma`al Ghair' lain) membuat saudara perempuan penuh lebih memenuhi syarat untuk warisan daripada saudara tiri dari ayah. Jika kasusnya melibatkan dua saudara perempuan kandung dan saudara tiri dari ayah, saudara tiri dari ayah sedarah dengan perbandingan 1:2 sisanya dengan saudara tiri dari ayah. Jika tidak ada situasi di atas yang terjadi, maka satu saudara tiri dari ayah mendapat setengah, dan dua atau lebih berbagi dua pertiga. Jika situasinya hanya melibatkan satu saudara perempuan, saudara tiri dari ayah mendapat seperenam sehingga melengkapi dua pertiga seolah-olah mereka berdua saudara kandung. Jika situasinya hanya melibatkan saudara tiri dari ayah maka saudara tiri dari ayah sedarah dengan perbandingan 1:2 dengan mereka. Jika keadaan hanya melibatkan anak perempuan atau anak perempuan dari anak laki-laki, maka saudara tiri dari ayah mendapatkan sisanya setelah keturunan perempuan mendapatkan bagian yang disebutkan (Sabq[1])",

"_SiblingM_":"<em>Saudara dari ibu</em>: Sekolah hukum menafsirkan penyebutan saudara kandung dalam ayat 4:12 berarti saudara kandung dari pihak ibu saja dan karena itu memutuskan bahwa mereka mewarisi. Mereka mewarisi hanya jika ahli waris lainnya tidak termasuk keturunan laki-laki, misalnya, anak laki-laki, atau pewaris laki-laki, misalnya, ayah. Bagian satu saudara tiri dari ibu adalah seperenam dari harta warisan. Jika ada dua atau lebih, mereka berbagi sama di sepertiga (Sabeq[1])",

"_RelativeM_":"<em>Kerabat lainnya</em>: Klik <a href='relativesm.html'>di sini untuk detailnya</a>",

"_Agnates_":"Agnates adalah kerabat laki-laki dari orang yang meninggal dari pihak ayah. Dari mereka, hanya anak laki-laki dan ayah yang selalu mewarisi. Ayah dan ayah dari ayah dapat menggabungkan bagian yang disebutkan serta bagian dalam sisanya, dengan ini disebut keturunan. Keturunan lainnya, seperti keponakan, paman, dan sepupu (dalam urutan kekerabatan itu) dapat mewarisi sisanya ketika warisan tidak sepenuhnya diambil. Hanya kategori kekerabatan terdekat yang mewarisi. Mazhab fikih Jaafari tidak mengizinkan agnasi dan sebaliknya memberikan sisanya, jika ada, ke perbendaharaan Islam.",

"_Kalala_":"Situasi 'Kalala' adalah ketika ahli waris yang masih hidup tidak termasuk pewaris laki-laki atau keturunan laki-laki. Ayat 4:12 dan 4:176 menyebutkan dua kasus. Ayat 4:12 menyebutkannya dalam konteks pasangan yang masih hidup dan ayat 4:176 menyebutkannya dalam konteks tidak ada pasangan yang masih hidup. Opsi 'Tidak ada preferensi' dari preferensi sekolah hukum menggunakan kedua konteks tersebut. Mazhab hukum lainnya hanya menggunakan konteks tanpa pasangan dan telah menafsirkan ayat 4:12 untuk berbicara tentang saudara tiri dari pihak ibu."
};

/**
 *	Explanations that can be referred to by their Id.
 *	Listed as one long JSON object simulating an associative array keyed by an Id,
 *	e.g., "Z1.1":"Explanation text".
 */
explanations = {
"_GFSibs_":"Dalam pendapat hukum yang dikaitkan dengan Ali (RA), dan diikuti oleh hukum Mesir, serta sekolah-sekolah hukum Syiah, kasus-kasus yang mencakup ayah dari ayah dan saudara kandung diputuskan sebagai berikut. Pertama, ahli waris yang bernama mendapat bagian yang disebutkannya, kemudian ayah dari ayah diberi bagian yang lebih baik dari tiga bagian: sepertiga dari sisanya, bagian laki-laki atau seperenam dari harta warisan. Sisanya dari ahli waris yang sedarah dengan sisanya. Jika saudara kandung hanya perempuan, ayah dari ayah mendapat bagian yang lebih baik dari dua bagian: sepertiga dari sisanya atau bagian laki-laki. Para saudara perempuan bersaudara di sisanya (Ibrahim [4])",
"_GFSibsZ_":"alam pendapat fikih yang dikaitkan dengan Zaid (RA), dan diikuti oleh mazhab Maliki, Syafii dan Hanbali, kasus-kasus yang mencakup ayah dari ayah dan saudara kandung diputuskan sebagai berikut. Pertama, ahli waris yang bernama mendapat bagian yang disebutkannya, kemudian ayah dari ayah diberi bagian yang lebih baik dari tiga bagian: sepertiga dari sisanya, bagian laki-laki atau seperenam dari harta warisan. Sisanya dari ahli waris yang sedarah dengan sisanya. Agnation memperhitungkan saudara kandung dari ayah tetapi tidak memberi mereka bagian mereka. Sebaliknya, bagian mereka diberikan kepada saudara kandung (Ibrahim [4])"
};

/**
 *	Display literals  that can be referred to by their Id.
 *	Listed as one long JSON object simulating an associative array keyed by an Id,
 *	e.g., "_gfather_":"Father/higher of father".
 */
displays = {
"_mustJS_":"<h1 align='center' style='text-align:center'>Halaman ini membutuhkan JavaScript 1.1</h1><p>Halaman ini membutuhkan browser yang mendukung JavaScript 1.1 atau lebih tinggi.</p><p>Browser Anda tidak mendukung JavaScript v1.1, atau JavaScript telah dinonaktifkan. Jika Anda ingin melihat halaman ini dengan benar, harap tingkatkan versi browser Anda atau aktifkan dukungan JavaScript.</p>",
"_noIE_":"Browser tidak kompatibel. Harap gunakan browser yang lebih modern, seperti Firefox",
"_attrlang_":"lang='id'",
"_attrdir_":"dir='ltr'",
"_bodyclass_":"",
"_bodypopup_":"class='arabic popup'",
"_autotranslate_":"",
"_RTLarrows_":"",
"_improvetranslation_":"Terjemahan otomatis. Jika Anda dapat memperbaikinya, <a href='mailto:islamicsoftware.org@gmail.com?subject=A better translation'>beri tahu kami</a><br/>",
"_autotranslatedetails_":"",
"_IRTH_":"IRTH",
"_IrthVersion_":"v2(Beta)",
"_title47_":"Pembagian yang ditentukan. (Quran 4:7) ",
"_alt47_":"Pembagian yang ditentukan. (Quran 4:7) ",
"_title411_":"Ditahbiskan oleh Tuhan. (Quran 4:11)",
"_alt411_":"Ditahbiskan oleh Tuhan. (Quran 4:11)",
"_IslamicInheritance_":"Warisan Islam",
"_Home_":"Beranda",
"_Questions_":"Pertanyaan",
"_Help_":"Bantuan ",
"_wizTitle_":"Antarmuka langkah-langkah ke program IRTH.",
"_Wizard_":"langkah-langkah ",
"_classicanchor_":"Klasik",
"_titleclassic_":"Antarmuka asli ke program IRTH",
"_Download_":"Unduh",
"_volunteeranchor_":"Partisipate",
"_v1stmt_":"document.writeln('<span id='oldlink' title='Versi lama dari program IRTH'>|<a href='../../v1/'>v1</a></span>');",
"_Number_":"Jumlah",
"_Heirs_":"Ahli Waris",
"_Share_":"Bagikan",
"_Junior_":"Muda",
"_wizStep1_":"1. Tentukan ahli waris",
"_wizStep2_":"2. Setel preferensi",
"_wizStep3_":"3. Distribusi harta warisan",

/* Versions */
"_MenuOption_":"<option value='irth.html'>Halaman</option>",
"_ClassicOption_":"<option value='./'>Klassik</option>",
"_WizardOption_":"<option value='irthwiz.html'>langkah-langkah</option>",
"_Version1Option_":"<option value='../../v1/'>Versi 1</option>",

/* Help pages */
"_UsageOption_":"<option value='irthhelp.html'>Tolong</option>",
"_QuestionsOption_":"<option value='questions.html'>Pertanyaan</option>",
"_DownloadOption_":"<option value='local.html'>Unduh</option>",
"_ParticipateOption_":"<option value='volunteer.html'>Ikut</option>",
"_HomePageOption_":"<option value='http://www.islamicsoftware.org'>Rumah</option>",

/* Languages */
"_Indonesian_":"<option value='id'>Indonesia</option>",
"_English_":"<option value='en'>English</option>",
"_Arabic_":"<option value='ar'>عربي</option>",
"_Urdu_":"<option value='ur''>اردو</option>",
"_Uighur_":"<option value='ug''>ئۇيغۇر</option>",
"_Pashto_":"<option value='ps''>پښتو</option>",
"_Farsi_":"<option value='fa''>فارسی</option>",
"_Kurdish_":"<option value='ku''>کوردی</option>",
"_Dhivehi_":"<option value='dv'' disabled>ދިވެހި</option>",
"_Afrikaans_":"<option value='af''>Afrikaans</option>",
"_Somali_":"<option value='so''>Af-Soomaali</option>",
"_Azeri_":"<option value='az''>Azərbaycan</option>",
"_Bosnian_":"<option value='bo''>босански</option>",
"_German_":"<option value='de''>Deutsch</option>",
"_Spanish_":"<option value='es''>Español</option>",
"_French_":"<option value='fr''>Français</option>",
"_Hausa_":"<option value='ha''>Hausa</option>",
"_Javanese_":"<option value='jv''>Jạwi</option>",
"_Kazakh_":"<option value='kk''>Қазақ</option>",	  
"_Swahili_":"<option value='sw''>Kiswahili</option>",
"_Malay_":"<option value='ms''>Melayu</option>",
"_Dutch_":"<option value='nl''>Nederlands</option>",
"_Portuguese_":"<option value='pt''>Português</option>",
"_Albanian_":"<option value='sq''>Shqip</option>", 
"_Turkish_":"<option value='tr''>Türk</option>",
"_Turkmen_":"<option value='tk''>Türkmen</option>",
"_Chechen_":"<option value='ce''>Содержани</option>",
"_Chinese_":"<option value='cn''>中文</option>",
"_Kyrgyz_":"<option value='ky''>Кыргызча</option>",
"_Russian_":"<option value='ru''>Pусский</option>",
"_Tajik_":"<option value='tg''>тоҷикӣ</option>",
"_Uzbek_":"<option value='uz''>ўзбекча</option>",
"_Bengali_":"<option value='bn''>বাংলা বর্ণমালা</option>",
"_Hindi_":"<option value='hi''>हिंदी</option>",
"_Kashmiri_":"<option value='ks''>कॉशुर</option>",
"_Thai_":"<option value='th''>ภาษาไทย</option>",
"_Rohingya_":"<option value='rh' disabled/>رُاَينڠَ</option>",
"_Amharic_":"<option value='am''>አማርኛ</option>",
"_OtherLanguage_":"<option value='ot'>Bahasa Lain</option>",

/* Float fix */
"_floatfix_":"left",

/* Heir categories and their conjugations */
/* Suffixes:- none: indefinite nominative, D: definite, O: accusative (object)), G: genetive, 2: dual */
"_Relation_":"Kekerabatan",
"_Bequest1-3_":"Wasiat (pecahan rasional <= 1/3)",

"_Son_":"Putra",
"_SonD_":"Anak laki-laki",
"_SonO_":"putranya",
"_SonDO_":"anak-anakya",
"_SonG_":"putra",
"_SonDG_":"putra",
"_Sons2_":"Dua putra",
"_Sons2D_":"Kedua putra",
"_Sons2O_":"dua putranya",
"_Sons2DO_":"kedua putranya",
"_Sons2G_":"dua putra",
"_Sons2DG_":"kedua putra",
"_Sons_":"Anak laki-laki",
"_SonsD_":"Anak laki-laki",
"_SonsO_":"anak laki-laki",
"_SonsDO_":"anak laki-laki",
"_SonsG_":"anak laki-laki",
"_SonsDG_":"anak laki-laki",

"_Daughter_":"Putri",
"_DaughterD_":"Anak perempuan",
"_DaughterO_":"putrinya",
"_DaughterDO_":"putrinya",
"_DaughterG_":"anak perempuan",
"_DaughterDG_":"anak perempuan",
"_Daughters2_":"Dua anak perempuan",
"_Daughters2D_":"Kedua anak perempuan",
"_Daughters2O_":"dua putrinya",
"_Daughters2DO_":"kedua putrinya",
"_Daughters2G_":"dua anak perempuan",
"_Daughters2DG_":"kedua anak perempuan",
"_Daughters_":"Anak perempuan",
"_DaughtersD_":"Anak perempuan",
"_DaughtersO_":"putrinya",
"_DaughtersDO_":"putrinya",
"_DaughtersG_":"anak perempuan",
"_DaughtersDG_":"anak perempuan",

"_Father_":"Ayah",
"_FatherD_":"Ayah",
"_FatherO_":"ayah",
"_FatherDO_":"ayah",
"_FatherG_":"ayah",
"_FatherDG_":"ayah",

"_Mother_":"Ibu",
"_MotherD_":"Ibu",
"_MotherO_":"ibu",
"_MotherDO_":"ibu",
"_MotherG_":"ibu",
"_MotherDG_":"ibu",

"_Husband_":"Suami",
"_HusbandD_":"Suami",
"_HusbandO_":"suami",
"_HusbandDO_":"suami",
"_HusbandG_":"suami",
"_HusbandDG_":"suami",

"_Wife_":"Istri",
"_WifeD_":"Istri",
"_WifeO_":"istri",
"_WifeDO_":"istri",
"_WifeG_":"istri",
"_WifeDG_":"istri",
"_Wives_":"istri",

"_Brother_":"Kakak laki-laki",
"_BrotherD_":"Kakak laki-laki",
"_BrotherO_":"kakak laki-laki",
"_BrotherDO_":"kakak laki-laki",
"_BrotherG_":"kakak laki-laki",
"_BrotherDG_":"kakak laki-laki",
"_Brothers2_":"Dua kakak laki-laki",
"_Brothers2D_":"Kedua kakak laki-laki",
"_Brothers2O_":"dua kakak laki-laki",
"_Brothers2DO_":"dua kakak laki-laki",
"_Brothers2G_":"dua kakak laki-laki",
"_Brothers2DG_":"dua kakak laki-laki",
"_Brothers_":"Saudara kandung",
"_BrothersD_":"Saudara kandung",
"_BrothersO_":"saudara kandung",
"_BrothersDO_":"saudara kandung",
"_BrothersG_":"saudara kandung",
"_BrothersDG_":"saudara kandung",

"_Sister_":"Kakak perempuan penuh",
"_SisterD_":"Kakak perempuan penuh",
"_SisterO_":"kakak perempuan penuh",
"_SisterDO_":"kakak perempuan penuh",
"_SisterG_":"kakak perempuan penuh",
"_SisterDG_":"kakak perempuan penuh",
"_Sisters2_":"Dua kakak perempuan penuh",
"_Sisters2D_":"Kedua kakak perempuan penuh",
"_Sisters2O_":"dua kakak perempuan penuh",
"_Sisters2DO_":"kedua kakak perempuan penuh",
"_Sisters2G_":"dua kakak perempuan penuh",
"_Sisters2DG_":"kedua kakak perempuan penuh",
"_Sisters_":"Saudara perempuan penuh",
"_SistersD_":"Saudara perempuan penuh",
"_SistersO_":"saudara perempuan penuh",
"_SistersDO_":"saudara perempuan penuh",
"_SistersG_":"saudara perempuan penuh",
"_SistersDG_":"saudara perempuan penuh",

"_SiblingM_":"Saudara tiri dari pihak ibu",
"_Siblingm_":"Saudara tiri dari pihak ibu",
"_SiblingmD_":"Saudara tiri dari pihak ibu",
"_SiblingmO_":"saudara tiri dari pihak ibu",
"_SiblingmDO_":"saudara tiri dari pihak ibu",
"_SiblingmG_":"saudara tiri dari pihak ibu",
"_SiblingmDG_":"saudara tiri dari pihak ibu",
"_Siblingsm2_":"Dua saudara tiri dari pihak ibu",
"_Siblingsm2D_":"Kedua saudara tiri dari pihak ibu",
"_Siblingsm2O_":"dua saudara tiri dari pihak ibu",
"_Siblingsm2DO_":"kedua saudara tiri dari pihak ibu",
"_Siblingsm2G_":"dua saudara tiri dari pihak ibu",
"_Siblingsm2DG_":"kedua saudara tiri dari pihak ibu",
"_SiblingsM_":"Saudara tiri dari pihak ibu",
"_Siblingsm_":"Saudara tiri dari pihak ibu",
"_SiblingsmD_":"Saudara tiri dari pihak ibu",
"_SiblingsmO_":"saudara tiri dari pihak ibu",
"_SiblingsmDO_":"saudara tiri dari pihak ibu",
"_SiblingsmG_":"saudara tiri dari pihak ibu",
"_SiblingsmDG_":"saudara tiri dari pihak ibu",

"_Gson_":"Putra dari putra",
"_Grandson_":"Putra dari putra",
"_GrandsonD_":"Putra dari putra",
"_GrandsonO_":"putra dari putra",
"_GrandsonDO_":"putra dari putra",
"_GrandsonG_":"putra dari putra",
"_GrandsonDG_":"putra dari putra",
"_Grandsons2_":"Dua putra dari putra",
"_Grandsons2D_":"Kedua putra dari putra",
"_Grandsons2O_":"dua putra dari putra",
"_Grandsons2DO_":"kedua putra dari putra",
"_Grandsons2G_":"dua putra dari putra",
"_Grandsons2DG_":"kedua putra dari putra",
"_Gsons_":"Putra putra",
"_Grandsons_":"Putra putra",
"_GrandsonsD_":"Putra putra",
"_GrandsonsO_":"putra putra",
"_GrandsonsDO_":"putra putra",
"_GrandsonsG_":"putra putra",
"_GrandsonsDG_":"putra putra",

"_Gdaughter_":"Putri dari putra",
"_Granddaughter_":"Putri dari putra",
"_GranddaughterD_":"Putri dari putra",
"_GranddaughterO_":"putri dari putra",
"_GranddaughterDO_":"putri dari putra",
"_GranddaughterG_":"putri dari putra",
"_GranddaughterDG_":"putri dari putra",
"_Granddaughters2_":"Dua putri dari putra",
"_Granddaughters2D_":"Kedua putri dari putra",
"_Granddaughters2O_":"dua putri dari putra",
"_Granddaughters2DO_":"kedua putri dari putra",
"_Granddaughters2G_":"dua putri dari putra",
"_Granddaughters2DG_":"kedua putri dari putra",
"_Gdaughters_":"Putri dari putra",
"_Granddaughters_":"Putri dari putra",
"_GranddaughtersD_":"putri dari putra",
"_GranddaughtersO_":"putri dari putra",
"_GranddaughtersDO_":"putri dari putra",
"_GranddaughtersG_":"putri dari putra",
"_GranddaughtersDG_":"putri dari putra",

"_Gfather_":"Ayah^ dari Ayah",
"_Grandfather_":"Ayah dari Ayah",
"_GrandfatherD_":"Ayah dari Ayah",
"_GrandfatherO_":"ayah dari Ayah",
"_GrandfatherDO_":"Ayah dari Ayah",
"_GrandfatherG_":"ayah dari Ayahr",
"_GrandfatherDG_":"ayah dari Ayah",

"_GmotherF_":"Ibu^ dari Ayah",
"_Grandmotherf_":"Ibu dari Ayah",
"_GrandmotherfD_":"Ibu dari Ayah",
"_GrandmotherfO_":"ibu dari Ayah",
"_GrandmotherfDO_":"ibu dari Ayah",
"_GrandmotherfG_":"ibu dari Ayah",
"_GrandmotherfDG_":"ibu dari Ayah",

"_Uncle_":"Saudara kandung dari ayah",
"_UncleD_":"Saudara kandung dari ayah",
"_UncleO_":"saudara kandung dari ayah",
"_UncleDO_":"saudara kandung dari ayah",
"_UncleG_":"saudara kandung dari ayah",
"_UncleDG_":"saudara kandung dari ayah",
"_Uncles2_":"Dua saudara kandung dari ayah",
"_Uncles2D_":"Kedua saudara kandung dari ayah",
"_Uncles2O_":"dua saudara kandung dari ayah",
"_Uncles2DO_":"kedua saudara kandung dari ayah",
"_Uncles2G_":"dua saudara kandung dari ayah",
"_Uncles2DG_":"kedua saudara kandung dari ayah",
"_Uncles_":"Saudara kandung ayah",
"_UnclesD_":"Saudara kandung ayah",
"_UnclesO_":"saudara kandung ayah",
"_UnclesDO_":"saudara kandung ayah",
"_UnclesG_":"saudara kandung ayah",
"_UnclesDG_":"saudara kandung ayah",

"_UncleF_":"Saudara tiri dari pihak ayah dari ayah",
"_Unclef_":"Saudara tiri dari pihak ayah dari ayah",
"_UnclefD_":"Saudara tiri dari pihak ayah dari ayah",
"_UnclefO_":"saudara tiri dari pihak ayah dari ayah",
"_UnclefDO_":"saudara tiri dari pihak ayah dari ayah",
"_UnclefG_":"saudara tiri dari pihak ayah dari ayah",
"_UnclefDG_":"saudara tiri dari pihak ayah dari ayah",
"_Unclesf2_":"Dua saudara tiri dari pihak ayah dari ayah",
"_Unclesf2D_":"Kedua saudara tiri dari pihak ayah dari ayah",
"_Unclesf2O_":"dua saudara tiri dari pihak ayah dari ayah",
"_Unclesf2DO_":"kedua saudara tiri dari pihak ayah dari ayah",
"_Unclesf2G_":"dua saudara tiri dari pihak ayah dari ayah",
"_Unclesf2DG_":"kedua saudara tiri dari pihak ayah dari ayah",
"_UnclesF_":"Ayah tiri dari pihak ayah",
"_Unclesf_":"Ayah tiri dari pihak ayah",
"_UnclesfD_":"Ayah tiri dari pihak ayah",
"_UnclesfO_":"ayah tiri dari pihak ayah",
"_UnclesfDO_":"ayah tiri dari pihak ayah",
"_UnclesfG_":"ayah tiri dari pihak ayah",
"_UnclesfDG_":"ayah tiri dari pihak ayah",

"_BrotherF_":"Saudara tiri dari pihak ayah",
"_Brotherf_":"Saudara tiri dari pihak ayah",
"_BrotherfD_":"Saudara tiri dari pihak ayah",
"_BrotherfO_":"saudara tiri dari pihak ayah",
"_BrotherfDO_":"saudara tiri dari pihak ayah",
"_BrotherfG_":"saudara tiri dari pihak ayah",
"_BrotherfDG_":"saudara tiri dari pihak ayah",
"_Brothersf2_":"Dua saudara tiri dari pihak ayah",
"_Brothersf2D_":"Kedua saudara tiri dari pihak ayah",
"_Brothersf2O_":"dua saudara tiri dari pihak ayah",
"_Brothersf2DO_":"kedua saudara tiri dari pihak ayah",
"_Brothersf2G_":"dua saudara tiri dari pihak ayah",
"_Brothersf2DG_":"kedua saudara tiri dari pihak ayah",
"_BrothersF_":"Saudara tiri dari pihak ayah",
"_Brothersf_":"Saudara tiri dari pihak ayah",
"_BrothersfD_":"Saudara tiri dari pihak ayah",
"_BrothersfO_":"saudara tiri dari pihak ayah",
"_BrothersfDO_":"saudara tiri dari pihak ayah",
"_BrothersfG_":"saudara tiri dari pihak ayah",
"_BrothersfDG_":"saudara tiri dari pihak ayah",

"_SisterF_":"Kakak tiri dari pihak ayah", 
"_Sisterf_":"Kakak tiri dari pihak ayah",
"_SisterfD_":"Kakak tiri dari pihak ayah",
"_SisterfO_":"kakak tiri dari pihak ayah",
"_SisterfDO_":"kakak tiri dari pihak ayah",
"_SisterfG_":"kakak tiri dari pihak ayah",
"_SisterfDG_":"kakak tiri dari pihak ayah",
"_Sistersf2_":"Dua kakak tiri dari pihak ayah",
"_Sistersf2D_":"Kedua kakak tiri dari pihak ayah",
"_Sistersf2O_":"dua kakak tiri dari pihak ayah",
"_Sistersf2DO_":"kedua kakak tiri dari pihak ayah",
"_Sistersf2G_":"dua kakak tiri dari pihak ayah",
"_Sistersf2DG_":"kedua kakak tiri dari pihak ayah",
"_SistersF_":"Saudara tiri dari pihak ayah", 
"_Sistersf_":"Saudara tiri dari pihak ayah",
"_SistersfD_":"Saudara tiri dari pihak ayah",
"_SistersfO_":"saudara tiri dari pihak ayah",
"_SistersfDO_":"saudara tiri dari pihak ayah",
"_SistersfG_":"saudara tiri dari pihak ayah",
"_SistersfDG_":"saudara tiri dari pihak ayah",

"_RelativeM_":"Kerabat lainnya",
"_Relativem_":"Kerabat lainnya",
"_RelativemD_":"Kerabat lainnya",
"_RelativemO_":"kerabat lainnya",
"_RelativemDO_":"kerabat lainnya",
"_RelativemG_":"kerabat lainnya",
"_RelativemDG_":"kerabat lainnya",
"_Relativesm2_":"Dua kerabat lainnya",
"_Relativesm2D_":"Kedua kerabat lainnya",
"_Relativesm2O_":"dua kerabat lainnya",
"_Relativesm2DO_":"kedua kerabat lainnya",
"_Relativesm2G_":"dua kerabat lainnya",
"_Relativesm2DG_":"kedua kerabat lainnya",
"_RelativesM_":"Kerabat lainnya",
"_Relativesm_":"Kerabat lainnya",
"_RelativemsD_":"Kerabat lainnya",
"_RelativemsO_":"kerabat lainnya",
"_RelativemsDO_":"kerabat lainnya",
"_RelativemsG_":"kerabat lainnya",
"_RelativemsDG_":"kerabat lainnya",

"_Nephew_":"Putra dari saudara laki-laki penuh",
"_NephewD_":"Putra dari saudara laki-laki penuh",
"_NephewO_":"putra dari saudara laki-laki penuh",
"_NephewDO_":"putra dari saudara laki-laki penuh",
"_NephewG_":"putra dari saudara laki-laki penuh",
"_NephewDG_":"putra dari saudara laki-laki penuh",
"_Nephews2_":"Dua putra dari saudara laki-laki penuh",
"_Nephews2D_":"Kedua putra dari saudara laki-laki penuh",
"_Nephews2O_":"dua putra dari saudara laki-laki penuh",
"_Nephews2DO_":"kedua putra dari saudara laki-laki penuh",
"_Nephews2G_":"dua putra dari saudara laki-laki penuh",
"_Nephews2DG_":"kedua putra dari saudara laki-laki penuh",
"_Nephews_":"Putra dari saudara kandung",
"_NephewsD_":"putra dari saudara kandung",
"_NephewsO_":"putra dari saudara kandung",
"_NephewsDO_":"putra dari saudara kandung",
"_NephewsG_":"putra dari saudara kandung",
"_NephewsDG_":"putra dari saudara kandung",

"_NephewF_":"Anak dari saudara tiri dari pihak ayah",
"_Nephewf_":"Anak dari saudara tiri dari pihak ayah",
"_NephewfD_":"Anak dari saudara tiri dari pihak ayah",
"_NephewfO_":"anak dari saudara tiri dari pihak ayah",
"_NephewfDO_":"anak dari saudara tiri dari pihak ayah",
"_NephewfG_":"anak dari saudara tiri dari pihak ayah",
"_NephewfDG_":"anak dari saudara tiri dari pihak ayah",
"_Nephewsf2_":"Dua anak dari saudara tiri dari pihak ayah",
"_Nephewsf2D_":"Kedua anak dari saudara tiri dari pihak ayah",
"_Nephewsf2O_":"dua anak dari saudara tiri dari pihak ayah",
"_Nephewsf2DO_":"kedua anak dari saudara tiri dari pihak ayah",
"_Nephewsf2G_":"dua anak dari saudara tiri dari pihak ayah",
"_Nephewsf2DG_":"kedua anak dari saudara tiri dari pihak ayah",
"_NephewsF_":"Putra dari saudara tiri dari pihak ayah",
"_Nephewsf_":"Putra dari saudara tiri dari pihak ayah",
"_NephewsfD_":"Putra dari saudara tiri dari pihak ayah",
"_NephewsfO_":"putra dari saudara tiri dari pihak ayah",
"_NephewsfDO_":"putra dari saudara tiri dari pihak ayah",
"_NephewsfG_":"putra dari saudara tiri dari pihak ayah",
"_NephewsfDG_":"putra dari saudara tiri dari pihak ayah",

"_GmotherM_":"Ibu^ dari Ibu",
"_Grandmotherm_":"Ibu dari Ibu",
"_GrandmothermD_":"Ibu dari Ibu",
"_GrandmothermO_":"ibu dari Ibu",
"_GrandmothermDO_":"ibu dari Ibu",
"_GrandmothermG_":"ibu dari Ibu",
"_GrandmothermDG_":"ibu dari Ibu",

"_Grandmother_":"Nenek",
"_Grandmothers_":"Nenek",

"_Cousin_":"Putra dari saudara kandung ayah",
"_CousinD_":"Putra dari saudara kandung ayah",
"_CousinO_":"putra dari saudara kandung ayah",
"_CousinDO_":"putra dari saudara kandung ayah",
"_CousinG_":"putra dari saudara kandung ayah",
"_CousinDG_":"putra dari saudara kandung ayah",
"_Cousins2_":"Dua putra dari saudara kandung ayah",
"_Cousins2D_":"Kedua putra dari saudara kandung ayah",
"_Cousins2O_":"dua putra dari saudara kandung ayah",
"_Cousins2DO_":"kedua putra dari saudara kandung ayah",
"_Cousins2G_":"dua putra dari saudara kandung ayah",
"_Cousins2DG_":"kedua putra dari saudara kandung ayah",
"_Cousins_":"Putra dari saudara kandung ayah",
"_CousinsD_":"Putra dari saudara kandung ayah",
"_CousinsO_":"putra dari saudara kandung ayah",
"_CousinsDO_":"putra dari saudara kandung ayah",
"_CousinsG_":"putra dari saudara kandung ayah",
"_CousinsDG_":"putra dari saudara kandung ayah",

"_CousinF_":"Anak dari saudara tiri ayah dari ayah",
"_Cousinf_":"Anak dari saudara tiri ayah dari ayah",
"_CousinfD_":"Anak dari saudara tiri ayah dari ayah",
"_CousinfO_":"anak dari saudara tiri ayah dari ayah",
"_CousinfDO_":"anak dari saudara tiri ayah dari ayah",
"_CousinfG_":"anak dari saudara tiri ayah dari ayah",
"_CousinfDG_":"anak dari saudara tiri ayah dari ayah",
"_Cousinsf2_":"Dua anak dari saudara tiri ayah dari ayah",
"_Cousinsf2D_":"Kedua anak dari saudara tiri ayah dari ayah",
"_Cousinsf2O_":"dua anak dari saudara tiri ayah dari ayah",
"_Cousinsf2DO_":"kedua anak dari saudara tiri ayah dari ayah",
"_Cousinsf2G_":"dua anak dari saudara tiri ayah dari ayah",
"_Cousinsf2DG_":"kedua anak dari saudara tiri ayah dari ayah",
"_CousinsF_":"Anak dari saudara tiri ayah dari ayah",
"_Cousinsf_":"Anak dari saudara tiri ayah dari ayah",
"_CousinsfD_":"anak dari saudara tiri ayah dari ayah",
"_CousinsfO_":"anak dari saudara tiri ayah dari ayah",
"_CousinsfDO_":"anak dari saudara tiri ayah dari ayah",
"_CousinsfG_":"anak dari saudara tiri ayah dari ayah",
"_CousinsfDG_":"anak dari saudara tiri ayah dari ayah",

"_Servant_":"Pelayan",
"_Servant_":"Pelayan",
"_ServantD_":"Pelayan",
"_ServantO_":"pelayan",
"_ServantDO_":"pelayan",
"_ServantG_":"pelayan",
"_ServantDG_":"pelayan",
"_Servants2_":"Dua pelayan",
"_Servants2D_":"Kedua pelayan",
"_Servants2O_":"pelayan",
"_Servants2DO_":"kedua pelayan",
"_Servants2G_":"pelayan",
"_Servants2DG_":"kedua pelayan",
"_Servants_":"Pelayan",
"_ServantsD_":"Pelayan",
"_ServantsO_":"pelayan",
"_ServantsDO_":"pelayan",
"_ServantsG_":"pelayan",
"_ServantsDG_":"pelayan",

"_Bequest_":"Wasiat selain ahli waris",
"_BequestD_":"Wasiat selain ahli waris",

"_Treasury_":"Perbendaharaan Islam",

/* Other conjugations */
"_each_":"masing-masing",
"_eachF_":"masing-masing",
"_each2_":"masing-masing",
"_each2F_":"masing-masing",
"_eachgets_":"masing-masing mendapat",
"_eachgetsF_":"masing-masing mendapat",
"_eachgets2_":"masing-masing mendapat",
"_eachgets2F_":"masing-masing mendapat",
"_gets_":"mendapat",
"_getsF_":"mendapat",
"_gets0_":"tidak mewarisi",
"_gets0F_":"tidak mewarisi",
"_get_":"mendapatkan",
"_getF_":"mendapatkan",
"_get0_":"tidak mewarisi",
"_get0F_":"tidak mewarisi",
"_get2_":"mendapatkan",
"_get2F_":"mendapatkan",
"_get02_":"tidak mewarisi",
"_get02F_":"tidak mewarisi",
"_noshare_":"0",
"_noshareF_":"0",
"_noshares2_":"0",
"_noshares2F_":"0",
"_noshares_":"0",
"_nosharesF_":"0",
"_has_":"punya",
"_hasF_":"punya",
"_have_":"memiliki",
"_haveF_":"memiliki",
"_have2_":"memiliki",
"_have2F_":"memiliki",
"_fracNONE_":"TIDAK",
"_fracTOSHARE_":"UNTUK BERBAGI",
"_fracWHOLE_":"SELURUH",

/* Tooltips */
"_ttss_":"Putra dari putri diklasifikasikan sebagai kerabat uterus dan harus dimasukkan dalam 'Kerabat lain'",
"_ttds_":"Anak perempuan dari anak perempuan diklasifikasikan sebagai kerabat uterus dan harus dimasukkan dalam 'Kerabat lain'",
"_ttgf_":"Ayah dari ibu diklasifikasikan sebagai kerabat uterus dan harus dimasukkan dalam 'Kerabat lain'",
"_ttun_":"Saudara laki-laki dan perempuan penuh ibu, serta saudara perempuan penuh ayah, diklasifikasikan sebagai saudara kandung dan harus dimasukkan dalam 'Kerabat lain'",
"_ttunf_":"Saudara laki-laki dan perempuan tiri ibu, serta saudara perempuan tiri ayah, diklasifikasikan sebagai saudara kandung dan harus dimasukkan dalam 'Kerabat lain'",
"_ttnw_":"Putra dan putri dari saudara perempuan penuh, serta putri dari saudara laki-laki penuh, diklasifikasikan sebagai kerabat uterus dan harus dimasukkan dalam 'Kerabat lain'",
"_ttnwf_":"Putra dan putri dari saudara tiri, serta putri dari saudara tiri, diklasifikasikan sebagai kerabat uterus dan harus dimasukkan dalam 'Kerabat lain'",
"_ttcz_":"Putra dan putri dari saudara laki-laki dan perempuan penuh dari ibu, serta anak perempuan dari saudara laki-laki dan perempuan penuh dari ayah atau ibu, diklasifikasikan sebagai kerabat uterus dan harus dimasukkan dalam 'Kerabat lain'",
"_ttczf_":"Anak laki-laki dan perempuan dari saudara tiri laki-laki dan perempuan dari ibu, serta anak perempuan dari saudara laki-laki dan perempuan tiri dari ayah atau ibu, diklasifikasikan sebagai saudara kandung dan harus dimasukkan dalam 'Kerabat lain '",
"_ttsrv_":"Laki-laki",

/* Buttons */
"_Calculate_":"Hitung",
"_Clear_":"Mulai Lagi",
"_Details_":"Rinciannya",
"_>>_":">>",
"_<<_":"<<",
"_BackToTop_":"Kembali keHalaman Entri",
"_ResetPrefs_":"Preferensi Pengaturan Ulang",
"_Add_":"Menambahkan",
"_Remove_":"Menghapus",
"_Reset_":"Mulai Lagi",
"_wizbtnDetails_":"Rinciannya",

/* Preferences */
"_Preferences_":"Preferensi",
"_optAllowed_":"Diizinkan",
"_optNotAllowed_":"Tidak diperbolehkan ",
"_titlebq_":"Wasiat, yang dinyatakan sebagai bagian rasional dari harta warisan, tidak melebihi 1/3",
"_titlerudd_":"Apakah akan mengizinkan pembagian sisa harta warisan yang belum berlangganan kepada ahli waris yang disebutkan. Jika tidak diizinkan, sisanya masuk ke kas Islam",
"_titleawl_":"Apakah akan mengizinkan pembagian kembali perkebunan yang kelebihan permintaan berdasarkan rasio proporsinya satu sama lain. Jika tidak diperbolehkan, kelebihannya dikurangkan dari bagian ahli waris perempuan terjauh",

/* Jusristic schools */
"_School_":"Sekolah hukum",
"_wizSchool_":"Sekolah hukum",
"_titleSchool_":"Mazhab",
"_explSchool_":"Sekolah yuristik mungkin memiliki pendapat berbeda tentang cara membagi perkebunan. Pilih sekolah hukum yang Anda ikuti atau lebih suka untuk diikuti. Jika Anda tidak mengikuti sekolah hukum tertentu, Anda dapat memilih 'Tidak ada preferensi'. Defaultnya adalah sekolah hukum Abu-Haneefa.",
"_Hanafi_":"Hanafi",
"_Maliki_":"Maliki",
"_Shafii_":"Syafii",
"_Hanbali_":"Hanbali",
"_Zahiri_":"Zahiri",
"_Egypt_":"Hukum Mesir",
"_Jaafari_":"Jaafari",
"_Ibadhi_":"Ibadhi",
"_Zaidi_":"Zaidi",
"_none_":"Tidak ada",
"_None_":"Tidak ada preferensi",

/* Oversubscription */
"_Oversub_":"Preferensi langganan berlebih",
"_explOversub_":"Jika jumlah saham yang dibagikan <em>lebih</em> dari harta warisan, apa yang Anda pilih untuk mereset saham tersebut?",
"_explOversub1_":"Membagi kembali semua saham dengan rasionya satu sama lain (Konsensus)",
"_explOversub0_":"Mengurangi bagian ahli waris wanita terjauh (Zahiri/Jaafari) ",
"_awlrule_":"Aturan Pembagian Ulang",

/* Undersubscription */
"_Undersub_":"Preferensi membatalkan langganan",
"_explUndersub_":"Jika jumlah saham yang dibagikan <em>kurang</em> dari warisan, bagaimana Anda memilih untuk membagikan sisanya?",
"_explUndersub1_":"Bagilah di antara ahli waris yang disebutkan dengan rasio satu sama lain dari bagian yang mereka sebutkan (Konsensus)",
"_explUndersub2_":"Sertakan pasangan dalam pemisah (Utsman)",
"_explUndersub0_":"Berikan ke perbendaharaan Islam (Maliki)",
"_ruddrule_":"Aturan Pembalikan",
"_optExtSpouses_":"Diperluas ke Pasangan",

/* Test cases */
"_TestCases_":"Kasus Uji",
"_Case_":"Kasus",
"_of_":"dari",
"_AbuBakr_":"Abu-Bakr",
"_Omaria_":"Gharraia (Omar)",
"_Minbaria_":"Minbaria (Ali)",
"_Shuraih_":"Hakim Syuraih",
"_Shafiia_":"Syafiia",
"_Kharqaa_":"Kharqaa",
"_Malikia_":"Malikia",
"_PseudoMalikia_":"Pseudo-Malikia",
"_Akdaria_":"Akdaria",
"_Mushtarika_":"Musytarika",
"_Sons-Daughters_":"Putra dan putri ",
"_Daughters-nosons_":"Putri dan tidak ada putri",
"_Daughters-Siblings_":"Putri dan saudara kandung",
"_Parents_":"Orangtua",
"_Grandfather-Siblings_":"Kakek dan saudara kandung",
"_Spouses_":"Pasangan",
"_SoleHeir_":"Hanya ahli waris",
"_NoHeirs_":"Tidak ada ahli waris",
"_RandomCase_":"kasus acak",
"_RandomHeirs_":"ahli waris acak",
"_AllTests_":"semua kasus",

/* Messages */
"_BUG_":"BUG",
"_calcerror_":"Kesalahan selama penghitungan saham",
"_calcnotok_":"Penghitungan tidak selesai",
"_calcok_":"Perhitungan selesai",
"_daughtersfail_":"Anak perempuan tidak mewarisi",
"_fatherfail_":"Sang ayah tidak mewarisi ",
"_husbandfail_":"Suami tidak mewarisi",
"_inputinvalid_":"Terjadi kesalahan selama validasi input. Harap perbaiki dan coba lagi",
"_motherfail_":"Sang ibu tidak mewarisi",
"_rangefail_":"Penghitungan kisaran ahli waris gagal",
"_redivfail_":"Harta warisan tidak sepenuhnya berlangganan setelah revisi",
"_reportit_":"Silakan laporkan ke penulis",
"_sonsfail_":"Anak laki-laki tidak mewarisi",
"_spouse2_":"Masukan yang salah dari suami dan istri",
"_startover_":"Tolong mulai lagi",
"_sumfail_":"Setelah asaba dan revisi, jumlah akhir saham menjadi pendek",
"_wifefail_":"istri tidak mewarisi",

/* Status */
"_bequest_":"Wasiat",
"_fullrev_":"Pengembalian penuh",
"_norev_":"Tidak ada pengembalian",
"_rediv_":"Tidak ada revisi",
"_rev_":"Pengembalian ",
"_thanks_":"Terima kasih telah mengunjungi IslamicSoftware.org",
"_translating_":"Menerjemahkan Ke",

/* Footer */
"_benefits_":"Semoga Tuhan menerima pekerjaan ini dan mengubahnya menjadi 'ilmu yang bermanfaat.'",
"_altCopyright_":"Lisensi Creative Commons CC-BY-NC-ND",
"_titleCopyright_":"Lisensi Creative Commons CC-BY-NC-ND",
"_lastupdate_":"23 Juni 2021-13 Zul Qi'dah 1442",
"_Copyright_":"&copy;&nbsp;1989+&nbsp;<a href='mailto:IslamicSoftware.org@gmail.com?subject=About your IRTH program'>IslamicSoftware.org</a>&nbsp;Lisensi CC-BY-NC-ND.<br/>Desain logo oleh Shaddim; simbol lisensi CC asli oleh Creative Commons [<a href='https://creativecommons.org/licenses/by/4.0'>CC BY 4.0</a>], <a href='https://commons.wikimedia.org/wiki/File:Creative_commons_license_spectrum.svg'>melalui Wikimedia Commons</a>",
"_Copyrightlogofloat_":"right",
"_Copyrightfloat_":"left",

/* Details */
"_Results_":"IRTH Hasil",

"_comma_":",",
"_semicolon_":";",

"_is_":"",

"_START_":"***** MULAILAH *****",

"_correct1_":"Nomor dikoreksi menjadi 0",
"_correct1_":"Nomor dikoreksi menjadi 1",
"_correct2_":"Nilai dikoreksi menjadi 1/3",
"_correct2_":"Nomor dikoreksi menjadi 2",
"_correct4_":"Nomor dikoreksi menjadi 4",

"_deprived_":"tidak mewarisi",
"_depriveds_":"tidak mewarisi",

"_iskalala_":"Situasi 'Kalala': Tidak ada keturunan atau penguasa yang hidup",

/* sumUp */
"_addsup_":"Memeriksa apakah pembagian bertambah...",
"_calcremain_":"Menghitung sisanya...",
"_doesaddup_":"Harta warisan sepenuhnya berlangganan",
"_finalsum_":"<b>*** Menambahkan semuanya ***</b>",
"_Finalsum_":"<b>*** Penjumlahan akhir ***</b>",
"_notaddupag_":"Setelah dibagikan kepada ahli waris 'asaba', bagiannya belum sama dengan harta warisan",
"_notfullrudd_":"Tidak sepenuhnya berlangganan setelah 'rudd' (pengembalian)",
"_notfullagrudd_":"Tidak sepenuhnya berlangganan setelah 'taasib' dan 'rudd' (pengembalian)",
"_remainnow_":"Sisa",
"_sumnow_":"Jumlah",
"_sumtreasury_":"Menjumlahkan untuk memeriksa bahwa perbendaharaan mendapatkan sisanya...",

"_theEnd_":"*** PERHITUNGAN SELESAI ***",

"_Noheirs_":"Tidak ada ahli waris",

/* calcnamedshare */
"_calcnamed_":"Menghitung saham ahli waris yang ditentukan...",
"_calcnamed1_":"Menghitung bagian yang ditahbiskan untuk",
"_daughters_":"Tidak ada anak laki-laki yang selamat. Satu anak perempuan mendapat setengahnya. Dua atau lebih mendapat dua pertiga",
"_daughters12_":"Anak perempuan berbagi dengan anak laki-laki dengan perbandingan 1:2",
"_fasaba_":"Situasi 'perempuan agnation': Tidak ada keturunan laki-laki kecuali satu anak perempuan, saudara perempuan atau saudara tiri dari ayah, jadi anak perempuan dari anak laki-laki mendapatkan seperenam untuk menyelesaikan dua pertiga",
"_fasabasis_":"Situasi 'perempuan agnation'. Saudari penuh akan berbagi dengan agnation dengan keturunan perempuan",
"_fasabasisF_":"Adik tiri dari pihak ayah tidak mewarisi dalam situasi 'perempuan agnation",
"_father6_":"Kedua orang tua selamat. Ayah juga mendapat seperenam",
"_fincalcnamed1_":"Selesai menghitung pangsa bernama",
"_fincalcnamed_":"Selesai menghitung bagian dari ahli waris yang disebutkan",
"_gdaughters_":"Tidak ada keturunan laki-laki. Satu anak perempuan dari anak laki-laki mendapat setengahnya. Dua atau lebih mendapat dua pertiga",
"_gdaughters0_":"Anak perempuan dari anak laki-laki tidak mewarisi dengan anak laki-laki",
"_gdaughters0a_":"Anak perempuan dari anak laki-laki tidak mewarisi jika anak perempuan lebih dari satu dan tidak ada anak laki-laki dari anak laki-laki (perempuan agnation tidak berlaku)",
"_gdaughters0b_":"Tidak ada aturan yang berlaku. Anak perempuan dari anak laki-laki tidak mendapat bagian",
"_gdaughters12gs_":"Putri dari putra menggantikan putri yang tidak bertahan",
"_gmother0_":"Nenek tidak mewarisi dengan ibu",
"_gmother36Z_":"Nenek menggantikan ibu yang tidak selamat. Mereka mendapat sepertiga atau keenam sesuai (Zahiri)",
"_gmother6_":"Ibu dari ayah dan ibu dari ibu adalah dari generasi yang sama, mereka berbagi keenam",
"_gmotherF0My_":"Ibu dari ayah tidak mewarisi karena ibu dari ibu adalah generasi yang lebih muda darinya",
"_gmotherF6M0_":"Tidak ada ibu dari ibu; ibu dari ayah mendapat seperenam (vonis Abu-Bakr)",
"_gmotherF6y_":"Ibu dari ayah mendapat seperenam karena dia generasi yang lebih muda dari ibu dari ibu",
"_gmotherJ_":"Di sekolah hukum Jaafari, semua nenek mendapat seperenam kecuali ibu selamat, dalam hal ini nenek tidak mewarisi",
"_gmotherM0Fy_":"Ibu dari ibu tidak mewarisi karena ibu bapak adalah generasi yang lebih muda darinya (mazhab Hanafi dan Hanbali)",
"_gmotherM6y_":"Ibu dari ibu mendapat yang keenam karena dia adalah generasi yang lebih muda dari ibu dari ayah",
"_gmotherM6F0_":"Tidak ada ibu dari ayah, ibu dari ibu mendapat seperenam (vonis Abu Bakar)",
"_gsons1_":"Putra dari putra menggantikan putra yang tidak bertahan",
"_gsons21d_":"Putra dari putra berbagi dengan anak perempuan dengan perbandingan 2:1",
"_higherTierJ_":"Di sekolah hukum Jaafari, ahli waris dalam tingkat yang lebih rendah tidak mewarisi jika ahli waris dalam tingkat yang lebih tinggi selamat",
"_husband4_":"Almarhum meninggalkan anak-anak atau cucu, suami mendapat kuartal",
"_husband2_":"Almarhum tidak meninggalkan anak atau cucu, suami mendapat setengah",
"_kalala1_":"Situasi 'Kalala' dengan pasangan yang masih hidup. Satu saudara mendapat seperenam. Lebih banyak berbagi sepertiga sama sama (4:12)",
"_kalalaJgfOK_":"Di sekolah hukum Jaafari, kehadiran seorang kakek diperbolehkan dalam menentukan situasi 'Kalala' (Ibrahim [3])",
"_mother3_":"Tidak ada keturunan, ayah atau saudara kandung. Ibu mendapat sepertiga",
"_mother3c_":"Ibu mendapat sepertiga dari sisanya dan ayah mendapat dua pertiga (keputusan Umar dan konsensus)",
"_mother3C_":"Ibu mendapat yang keenam dengan dua saudara kandung atau lebih (konsensus)",
"_mother3z_":"Ibu mendapat sepertiga dan ayah berbagi menurut agnation (Zahiri)",
"_mother3Z_":"Ibu mendapat sepertiga dengan saudara kandung kurang dari tiga (Zahiri)",
"_mother6_":"Yang meninggal meninggalkan keturunan, ibu mendapat seperenam",
"_mrdeprives_":"Karena sang ibu selamat",
"_mushtarika_":"Kasus Mushtarika: Saudara kandung dari ibu berbagi dengan saudara kandung (Maliki/Syafii)",
"_noasabaJ_":"Sekolah hukum Jaafari tidak mengizinkan 'Asaba",
"_nochptJ_":"Dalam mazhab Jaafari, cucu tidak mewarisi dengan orang tuanya",
"_nofasaba_":"Bukan situasi 'perempuan agnation'. Lebih dari satu anak perempuan, jadi dua pertiga sudah diberikan. Oleh karena itu, tidak ada yang boleh diberikan kepada anak perempuan dari anak laki-laki",
"_numsib_":"Jumlah saudara",
"_siblings3_":"Almarhum meninggalkan pasangan, ayah, ibu dan saudara kandung. Saudara berbagi sepertiga",
"_sibling6_":"Almarhum meninggalkan pasangan, ayah, ibu, dan saudara kandung. Saudara mendapat seperenam",
"_siblings6_":"Saudara mendapatkan keenam yang dikurangi dari bagian ibu",
"_siblingsM0MSB1_":"Saudara kandung dari pihak ibu tidak mewarisi ketika kakek masih hidup (Maliki/Syafii/Hanbali)",
"_siblingsM0MSB2_":"Saudara kandung pihak ibu tidak mewarisi jika anak perempuan (atau anak perempuan dari anak laki-laki) masih hidup (Hanafi/Maliki/Syafii/Hanbali)",
"_siblingM6_":"Satu saudara dari ibu mendapat seperenam",
"_siblingsM3_":"Lebih dari satu saudara dari ibu, mereka berbagi dalam satu ketiga",
"_sisters0_":"Saudara perempuan tidak mewarisi ketika ayahnya masih hidup",
"_sisters0HZI_":"Saudara perempuan tidak mewarisi ketika kakek masih hidup (Hanafi/Zahiri/Ibadhi)",
"_sisters12_":"Saudara perempuan penuh berbagi dengan saudara laki-laki penuh dengan perbandingan 1:2",
"_sistersMSB_":"Saudara perempuan penuh berbagi dengan ayah dari ayah dengan 'taasib' ( Maliki/Syafii/Hanbali/Hukum Mesir)",
"_sisters2_":"Satu saudara perempuan penuh dan tidak ada saudara laki-laki penuh, dia mendapat setengah",
"_sisters23_":"Lebih dari satu saudara perempuan dan tidak ada saudara laki-laki, mereka berbagi dua pertiga",
"_sistersF0_":"Adik tiri dari pihak ayah tidak mewarisi saat ayah masih hidup",
"_sistersF0m_":"Adik tiri dari pihak ayah tidak mewarisi ketika saudara kandung laki-laki atau keturunan laki-laki masih hidup",
"_sistersF0nofasaba1_":"Adik tiri dari pihak ayah tidak mewarisi jika ada lebih dari satu saudara perempuan kandung dan tidak ada saudara tiri dari pihak ayah ('Perempuan Asaba' tidak berlaku)",
"_sistersF0nofasaba2_":"Adik tiri dari pihak ayah tidak mewarisi jika ada satu saudara perempuan kandung dan satu atau lebih keturunan perempuan",
"_sistersF12_":"Adik tiri dari pihak ayah berbagi dengan saudara laki-laki tiri dari pihak ayah dengan perbandingan 1:2",
"_sistersF2_":"Satu saudara perempuan tiri dari pihak ayah dan tidak ada saudara laki-laki tiri dari pihak ayah. Dia mendapat setengah",
"_sistersF23_":"Lebih dari satu saudara perempuan tiri dari pihak ayah dan tidak ada saudara laki-laki tiri dari pihak ayah. Mereka berbagi dua pertiga",
"_sistersFHZI_":"Adik tiri dari pihak ayah tidak mewarisi ketika ayah dari ayah masih hidup (Hanafi/Zahiri/Ibadhi)",
"_sistersFMSB_":"Adik tiri dari pihak ayah berbagi secara 'taasib' dengan kakek (Maliki/Shafii/Hanbali)",
"_sistersFfasaba_":"Satu saudara perempuan dan tidak ada saudara laki-laki tiri dari pihak ayah dan tidak ada keturunan perempuan, jadi saudara perempuan tiri dari pihak ayah mendapatkan seperenam untuk menyelesaikan dua pertiga",
"_sistersFshare_":"Adik tiri dari pihak ayah akan berbagi dengan 'taasib'",
"_sumsofar_":"Meringkas distribusi saham sejauh ini...",
"_wife4_":"Almarhum tidak meninggalkan anak atau cucu, istri mendapat seperempat",
"_wife8_":"Almarhum meninggalkan anak atau cucu, istri mendapat seperdelapan",

/* calcagnateshare */
"_akdaria_":"Masalah Akdaria. Menetapkan bagian ayah dari ayah menjadi seperenam sebelum pembagian ulang",
"_agnates0_":"tidak mewarisi dengan kerabat dekat laki-laki",
"_agnates0a_":"jangan mewarisi dengan saudara perempuan dalam situasi 'perempuan agnation",
"_becausefull_":" karena warisan sekarang sepenuhnya berlangganan setelah menerapkan semua aturan",
"_brothers0_":"Saudara kandung tidak mewarisi dengan keturunan laki-laki atau dengan ayah",
"_brothers0HZ_":"Saudara kandung tidak mewarisi dengan ayah dari ayah (Hanafi/Zahiri)",
"_brothers_":"Saudara kandung boleh berbagi berdasarkan agnation",
"_brothersF_":"Saudara tiri dari pihak ayah dapat berbagi berdasarkan agnation",
"_brothersF0_":"Saudara laki-laki tiri dari pihak ayah tidak mewarisi dengan keturunan laki-laki atau dengan ayah",
"_brothersF0a_":"Saudara perempuan tiri dari pihak ayah tidak mewarisi dengan saudara perempuan penuh dalam situasi 'perempuan agnation'",
"_calcagnate1_":"Menyetel bagian agnate dari",
"_father_":"Almarhum tidak meninggalkan keturunan. Ayah mewarisi oleh keturunan agnation",
"_father6_":"Almarhum meninggalkan keturunan laki-laki. Ayah mendapat seperenam",
"_father6a_":"Almarhum meninggalkan keturunan perempuan. Ayah mendapat seperenam. Dia mungkin mendapatkan lebih banyak dengan agnation",
"_fatherdeprives_":"karena ayah selamat",
"_frdeprivesgmf_":"karena ayah selamat",
"_fincalcagnate_":"Selesai menetapkan bagian ahli waris agnate",
"_fincalcagnate1_":"Selesai membangun bagian agnation dari",
"_gfather_":"Almarhum tidak meninggalkan keturunan. Ayah dari ayah mewarisi oleh agnation",
"_gfather0_":"Ayah dari ayah tidak mewarisi dengan ayah",
"_gfather6_":"Almarhum meninggalkan keturunan laki-laki. Ayah dari ayah mendapat seperenam",
"_gfather6a_":"Almarhum meninggalkan keturunan perempuan. Ayah dari ayah mendapat seperenam. Dia mungkin mendapatkan lebih banyak dengan agnation",
"_gfdeprives_":"karena ayah dari ayah memiliki prioritas (Hanafi)",
"_gsondeprives_":"karena putra putra selamat",
"_gsons0_":"Anak-anak putra tidak mewarisi dengan anak laki-laki",
"_gsons_":"Anak-anak putra saham oleh agnation",
"_invalidheir_":" tidak indeks ahli waris yang sah",
"_noagnationJ_":"Agnation ('Asaba') tidak diperbolehkan di sekolah hukum Jaafari",
"_relativesM0MSZ_":"Kerabat lain tidak mewarisi (Maliki/Shafii/Zahiri)",
"_sondeprives_":"karena seorang putra selamat",
"_sons_":"Anak laki-laki akan berbagi dengan agnation",

"_xsons_":"Bagian anak laki-laki tidak boleh tidak ada",
"_xdaughters_":"Bagian anak perempuan tidak boleh tidak ada",
"_xfather_":"Bagian ayah tidak boleh tidak ada",
"_xmother_":"Bagian ibu tidak boleh tidak ada",
"_xhusband_":"Bagian suami tidak boleh tidak ada",
"_xwife_":"Bagian istri tidak boleh tidak ada",

/* Awl */
"_daughters-ZJ_":"Pembagian kembali harta warisan yang melebihi permintaan ('Awl') tidak diperbolehkan. Bagian anak perempuan dididik karena kelebihan permintaan (Zahiri/Jaafari)",
"_excess_":"Harta warisan kelebihan permintaan",
"_father3awl_":"Bagian ayah dikembalikan sepertiga sebelum dibagi kembali",
"_fathersum_":"Ringkasan sekarang karena pangsa ayah adalah ulang",
"_gdaughters-ZJ_":"Pembagian kembali harta warisan yang kelebihan permintaan tidak diperbolehkan. Bagian anak perempuan dari anak laki-laki berkurang karena kelebihan permintaan (Zahiri/Jaafari)",
"_gfather6awl_":"Bagian ayah dari ayah dikembalikan ke seperenam sebelum dibagi kembali. (Hukum Mesir/pendapat Ali)",
"_gfather3awl_":"Bagian ayah dari ayah dikembalikan ke sepertiga sebelum dibagi kembali. (Konsensus/pendapat Zaid)",
"_gfathersum_":"Ringkasan sekarang karena pangsa ayah dari aya adalah ulang",
"_isoversub_":"Terjadi kelebihan langganan",
"_noawl_":"Pembagian kembali harta warisan yang kelebihan permintaan tidak diperbolehkan. Ini adalah default untuk sekolah hukum Zahiri/Jaafari. Ibn Hazm mengikuti Ibn Abbas (RA) yang tidak menyetujui pembagian kembali dalam kasus kelebihan permintaan atas suatu harta warisan. disukai mengurangi bagian saudara perempuan atau anak perempuan. Sekolah hukum Jaafari setuju",
"_rediv_":"<b>*** Membagi Ulang ***</b>",
"_redivok_":"Jumlah saham yang benar setelah pembagian kembali",
"_sisters-ZJ_":"Pembagian kembali harta warisan yang kelebihan permintaan tidak diperbolehkan. Bagian saudara kandung berkurang karena kelebihan permintaan (Zahiri/Jaafari)",
"_sistersF-ZJ_":"Pembagian kembali harta warisan yang kelebihan permintaan tidak diperbolehkan. Bagian saudara perempuan dari pihak ayah berkurang karena kelebihan permintaan (Zahiri/Jaafari)",
"_sumoverunder_":"Penjumlahan untuk menentukan kelebihan atau kekurangan berlangganan...",
"_wrongrediv_":"redivide() dipanggil saat jumlah adalah",

/* agnate */
"_addsupfathers_":"Bagian bertambah setelah menangani kasus khusus ayah/kakek",
"_agnateshare_":"berbagi di agnation",
"_agnshare_":"Bagian agnate dari",
"_agplusnamed_":"Ayah, atau ayah dari ayah, mendapatkan bagian agnate mereka serta bagian bernama mereka",
"_applyag_":"<b>*** Menerapkan aturan agnation ***</b>",
"_brothersF23agZ_":"Dalam kasus kakek dan saudara kandung, saudara laki-laki tiri dari pihak ayah mendapatkan bagian dari saudara laki-laki ketika sisanya tidak mencakup bagian saudara perempuan yang disebutkan (Maliki/Shafii/Hanbali)",
"_brothersFZ_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara kandung, saudara laki-laki tiri dari pihak ayah mendapatkan sisanya dan saudara perempuan tiri dari pihak ayah tidak mendapatkan apa-apa (Maliki/Syafii/Hanbali)",
"_fatherag_":"Kasus khusus ayah dan tidak ada keturunan laki-laki. Dia mewarisi bagiannya yang ditentukan dan juga mewarisi menurut agnation",
"_finagn_":"Selesai menerapkan aturan agnation",
"_finaldeprive_":"Para ahli waris yang ditetapkan untuk berbagi tidak mendapatkan apa-apa jika tidak ada yang tersisa. Harta orang yang meninggal sekarang sepenuhnya dimiliki setelah menerapkan semua aturan",
"_getrem_":"dapatkan juga sisanya sebagai kerabat laki-laki terdekat",
"_getsrem_":"juga mendapat sisanya sebagai kerabat laki-laki terdekat",
"_gfatherag_":"Kasus khusus ayah dari ayah dan tidak ada keturunan laki-laki. Ia mewarisi bagian namanya dan menurut garis agnation",
"_gfatheragA_":"Dalam kasus kakek dan saudara kandung, ayah dari ayah mendapat bagian laki-laki biasa dari sisanya (hukum Ali/Hanafi/Mesir)",
"_gfather3ag6Z_":"Dalam kasus kakek dan saudara kandung, ayah dari ayah mendapat sepertiga dari sisanya, bagian milik saudara laki-laki atau seperenam dari harta orang yang meninggal, mana yang lebih besar (Maliki/Syafii/Hanbali)",
"_gfatheragAsis_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara laki-laki, ayah dari ayah mendapat bagian dari agnate laki-laki atau sepertiga dari sisanya, mana yang lebih besar (hukum Ali/Mesir)",
"_gfatheragSibH_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara laki-laki, ayah dari ayah mendapat sisanya dan saudara perempuan tidak mendapat bagian (Hanafi)",
"_gfather3Z_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara laki-laki, ayah dari ayah mendapat sepertiga dari sisa atau bagian agnate saudara laki-laki, mana yang lebih besar (Maliki/Syafii/Hanbali)",
"_lastdeprive_":" karena agnation dan/atau kelebihan permintaan telah diterapkan",
"_noaddupag_":"Distribusi masih belum lengkap setelah menerapkan aturan agnation",
"_nofatherfdec_":"Kasus bukan kasus ayah, keturunan perempuan dan tidak ada keturunan laki-laki",
"_nofasaba_":"Tidak ada 'agnation perempuan'",
"_notundersub_":"Harta warisan lebih dari jumlah saham",
"_regagshare_":" (bagian agnate)",
"_sistersagZ_":"Dalam kasus kakek dan saudara kandung, saudara perempuan penuh mendapatkan bagian agnate ditambah bagian saudara perempuan tiri dari pihak ayah, jika ada (Maliki/Syafii/Hanbali)",
"_sistersZ_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara laki-laki, saudara perempuan penuh mendapatkan bagian agnate ditambah bagian saudara perempuan dari pihak ayah, jika ada (Maliki/Syafii/Hanbali)",
"_sistersFZ_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara laki-laki atau saudara perempuan kandung, saudara tiri dari pihak ayah mendapatkan bagian agnate mereka yang kebetulan merupakan sisanya (Maliki/Syafii/Hanbali)",
"_sisters23agZ_":"Dalam kasus kakek dan saudara kandung, saudara perempuan penuh mendapatkan bagian yang disebutkan, setengah atau dua pertiga, ketika sisanya dapat menutupinya. Saudara tiri dari pihak ayah, dalam hal ini, tidak mendapatkan apa-apa. Saudara tiri dari pihak ayah mendapatkan bagian sisanya, yang boleh jadi tidak ada apa-apanya karena ayah dari bapak akan mengambil bagian yang lebih besar dari sepertiga atau bagian dari keturunan (Maliki/Syafii/Hanbali)",
"_sisters23ag2Z_":"Dalam kasus kakek dan saudara kandung, ketika tidak ada saudara laki-laki, saudara perempuan kandung mendapatkan bagian yang lebih kecil dari bagian mereka yang disebutkan, setengah atau dua pertiga, atau bagian agnate. Saudara tiri dari pihak ayah mendapatkan sisanya, jika ada (Maliki/Syafii/Hanbali)",
"_sumagn_":"Jumlah bobot agnation =",
"_sumaggfather_":"Ringkasan seandainya bagian ayah dari ayah melebihi bagian agnate",
"_sumcalcag1_":"Ringkasan setelah perhitungan agnation selesai untuk",
"_sumcalcfathers_":"Ringkasan sebelum menangani kasus khusus ayah/kakek...",
"_sumfatherfdec_":"Ringkasan sebelum menangani kemungkinan kasus khusus yang tersisa, misalnya, keturunan ayah dan wanita...",
"_sumfathers_":"Ringkasan jika bagian ayah berubah atau bagian ayah dari ayah berubah",
"_sumfasaba_":"Ringkasan sebelum memeriksa 'perempuan agnation'...",
"_sumsisagZ_":"Ringkasan seandainya bagian saudara perempuan berkurang dari bagian yang disebutkan",
"_wrongag_":"Aturan agnation tidak berlaku kecuali harta warisan kurang berlangganan",

/* Rudd */
"_doesnotrudd_":"tidak berpartisipasi dalam 'rudd' (pengembalian)",
"_donotrudd_":"tidak berpartisipasi dalam 'rudd' (pengembalian)",
"_noagrudd_":"Tidak ada keturunan, membagi sisa di antara ahli waris yang disebutkan dengan rasio bagian yang disebutkan",
"_norudd_":"Pengembalian ('Rudd') tidak diperbolehkan",
"_noruddMZ_":"Mengikuti mazhab Maliki/Zahairi yang tidak membolehkan 'rudd' (pembalikan)",
"_rev2_":"Pengembalian ('rudd') ke pasangan diperbolehkan",
"_doesrudd_":"berpartisipasi dalam 'rudd' (pengembalian)",
"_rudd2C_":"Mengikuti pendapat mayoritas yang tidak mengizinkan kembali ke pasangan",
"_ruddextra_":"Pengembalian diterapkan - Menambahkan bagian dari sisanya",
"_dorudd_":"berpartisipasi dalam 'rudd' (pengembalian)",
"_usernorudd_":"Pengguna lebih suka untuk tidak mengizinkan 'rudd' (pengembalian)",
"_userrudd_":"Pengguna lebih suka membiarkan 'rudd' (pengembalian)",
"_userrudd2_":"Pengguna lebih suka mengizinkan 'rudd' (pengembalian) juga untuk pasangan",

/* Results */
"_allowed_":"diizinkan",
"_asfollows_":"Setelah pembayaran biaya-biaya, hutang-hutang, dan kewajiban-kewajiban, sisa harta warisan itu harus dibagi sebagai berikut",
"_asfollowsnobq_":"Setelah pembayaran biaya-biaya, hutang-hutang, wasiat, dan kewajiban-kewajiban, maka sisa harta warisan itu dibagi sebagai berikut",
"_Bequest_":"Wasiat",
"_Calculating_":"*** Menghitung ***",
"_Collecting_":"*** Mengumpulkan masukan ***",
"_Correcting_":"*** Memvalidasi masukan ***",
"_Details_":"Rinciannya",
"_Displaying_":"*** Menampilkan hasil ***",
"_DISTRIBUTION_":"DISTRIBUSI HARTA WARISAN",
"_END_":"***** AKHIR *****",
"_Initializing_":"*** Inisialisasi ***",
"_NONE_":"TIDAK",
"_notallowed_":"tidak diperbolehkan",
"_Reversion_":"Pengembalian",
"_Reversion-s_":"Pengembalian ke pasangan",
"_Redivision_":"Pembagian ulang",
"_School_":"Sekolah hukum ",
"_tabALL_":"SELURUH",
"_tabAw_":"Pu",
"_tabBf_":"Sla",
"_tabBq_":"Ws",
"_tabBr_":"Sl",
"_tabCase_":"Kasus",
"_tabCf_":"Pta",
"_tabCz_":"Psa",
"_tabDr_":"Ap",
"_tabDs_":"Pip",
"_tabFr_":"Ay",
"_tabFull_":"Penuh",
"_tabGF_":"Aa",
"_tabGf_":"Ia",
"_tabGm_":"Ii",
"_tabHeirs_":"Ahli waris",
"_tabHb_":"Su",
"_tabMr_":"Ib",
"_tabNf_":"Kma",
"_tabNo_":"Tidak",
"_tabNu_":"Km",
"_tabOr_":"Kl",
"_tabRv_":"Pg",
"_tabSc_":"Sh",
"_tabSf_":"Spa",
"_tabShares_":"Berbagi",
"_tabSm_":"Si",
"_tabSn_":"Al",
"_tabSr_":"Slp",
"_tabSs_":"Pp",
"_tabSv_":"Pel",
"_tabTr_":"PI",
"_tabUf_":"Sta",
"_tabUn_":"Ska",
"_tabWf_":"Is",
"_tabYes_":"Iya",
"_THEHEIRS_":"AHLI WARIS",
"_tabLegend_":"Legenda:- Al:Anak laki-laki, Ap:Anak perempuan, Ay:Ayah, Ib:Ibu, Su:Suami, Is:Istri, Sl:Kakak laki-laki, Sp:Kakak perempuan, Si:Saudara tiri dari pihak ibu, Pp:Putra putra, Pip:Putri dari putra, Aa:Ayah dari ayah, Ia:Ibu dari ayah, Ska:Saudara kandung dari ayah, Sta:Saudara tiri dari ayah, Sla:Saudara laki-laki dari pihak ayah , Spa:Saudara perempuan dari pihak ayah , Kl:Kerabat lainnya, Km:Kemenakan, Kma:Anak laki-laki dari saudara tiri ayah, Ii:Ibu dari ibu, Psa:Putra dari saudara kandung ayah, Pta:Putra dari saudara tiri ayah dari ayah, Pel:Pelayan, PI:Perbendaharaan Islam, Sh:Sekolah hukum, Pg:Pengembalian, Pu:Pembagian ulang, Ws:Wasiat",

/* Test cases */
"_ALL_":"SELURUH",
"_Full_":"Penuh",
"_Heirs_":"Ahli waris",
"_No_":"Tidak",
"_testcase_":"Kasus uji #",
"_testok_":"Perhitungan kasus uji selesai",
"_Yes_":"Iya",

/* Special cases */
"_specialcase_":"Kasus khusus, Id:",
"_spacialfailed_":"Pemrosesan kasus khusus telah gagal",

/* Bequest & treasury */
"_bequest1_":"Wasiat diberikan terlebih dahulu",
"_reducedbq_":"bagiannya berkurang karena wasiat",
"_treasury1_":"Tidak ada ahli waris. Perbendaharaan mendapatkan harta warisan dikurangi warisan, jika ada",
"_treasury2_":"Ahli waris tunggal dan kembali ke pasangan tidak diperbolehkan. Perbendaharaan mendapatkan sisanya",
"_treasury3_":"Ahli waris tunggal dan pengembalian tidak diperbolehkan. Perbendaharaan mendapatkan sisanya",
"_treasury4_":"Perkebunan tidak sepenuhnya berlangganan setelah menerapkan semua aturan. Memberikan sisanya ke Perbendaharaan Islam"
};
